language: ruby
before_install: gem update --system
cache: bundler
sudo: false
rvm:
  - 2.5.1
before_script:
  - ./bin/rails db:migrate RAILS_ENV=test
  - cp spec/config.yml{.sample,}
script: bundle exec rspec
